services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: candy-stock-app
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    build: .docker/postgres
    container_name: candy-stock-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=candy-stock-secret
      - POSTGRES_DB=candy-stock
